## 1
name: Test and Deploy

## Actions that will be executed when you push code currently none
on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'Release Semantic Versioning (e.g. 4.15.2)'
        required: true
      track:
        description: 'Track'
        required: true
        default: internal
        type: choice
        options:
          - internal
          - alpha
          - beta
          - production

## 2
jobs:
  ## 3
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Unit tests
        run: ./gradlew test
  ## 4
  # android_tests:
  #  runs-on: [ macos-latest ]
  #  steps:
  #    - uses: actions/checkout@v2
#
  #    - name: Setup JDK
  #      uses: actions/setup-java@v3
  #      with:
  #        distribution: 'adopt'
  #        java-version: 11.0.14
#
  #    - name: Instrumentation Tests
  #      uses: reactivecircus/android-emulator-runner@v2
  #      with:
  #        api-level: 29
  #        script: ./gradlew connectedAndroidTest

  build:
    needs: [ unit_tests ]
    runs-on: ubuntu-latest
    steps:
      # 1
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release tag
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ github.event.inputs.semver }}",
              sha: context.sha
            })

      - name: Workaround to fetch the tag # Is there a better way to do it?
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # 2
      - name: Generate Release APK
        run: ./gradlew assembleRelease
      # 3
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_STORE_PASSWORD }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
      # 4
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/outputs/