## 1
name: Test and Deploy

## Actions that will be executed when you push code currently none
on:
  workflow_dispatch:

## 2
jobs:
  ## 3
  unit_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2

      - name: Unit tests
        run: ./gradlew test
  ## 4
  # android_tests:
  #  runs-on: [ macos-latest ]
  #  steps:
  #    - uses: actions/checkout@v2
#
  #    - name: Setup JDK
  #      uses: actions/setup-java@v3
  #      with:
  #        distribution: 'adopt'
  #        java-version: 11.0.14
#
  #    - name: Instrumentation Tests
  #      uses: reactivecircus/android-emulator-runner@v2
  #      with:
  #        api-level: 29
  #        script: ./gradlew connectedAndroidTest

  build:
    needs: [ unit_tests ]
    runs-on: ubuntu-latest
    steps:
      # 1
      - name: Checkout code
        uses: actions/checkout@v2
      # 2
      - name: Generate Release APK
        run: ./gradlew assembleRelease
      # 3
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_STORE_PASSWORD }}
          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
      # 4
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Build Artifacts
          path: app/build/outputs/